---
- name: sudoers | update
  lineinfile:
    dest: "/etc/sudoers.d/{{item.name}}"
    insertafter: EOF
    line: "{{ item.name }} ALL=NOPASSWD:ALL"
    regexp: "{{ item.name }} ALL=NOPASSWD:ALL"
    create: yes
  become: true
  when: "{{ item.sudoer }}"
  with_items: "{{ users }}"
